FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY . .

RUN \
  GOOS=wasip1 GOARCH=wasm go build -o ./cmd/atc/internal/testing/wasmcache/flight.wasm ./cmd/atc/internal/testing/apis/backend/flight && \
  go build -o ./bin/server ./cmd/atc/internal/testing/wasmcache

FROM alpine

COPY --from=builder /app/bin/server ./server

ENTRYPOINT ["./server"]

