FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN GOTOOLCHAIN=auto go mod download

COPY . .

RUN \
  GOTOOLCHAIN=auto GOOS=wasip1 GOARCH=wasm go build -o ./cmd/atc/internal/testing/wasmcache/wasm/flight.v1.wasm ./cmd/atc/internal/testing/apis/backend/v1/flight && \
  GOTOOLCHAIN=auto GOOS=wasip1 GOARCH=wasm go build -o ./cmd/atc/internal/testing/wasmcache/wasm/flight.v2.wasm ./cmd/atc/internal/testing/apis/backend/v2/flight && \
  GOTOOLCHAIN=auto GOOS=wasip1 GOARCH=wasm go build -o ./cmd/atc/internal/testing/wasmcache/wasm/flight.dev.wasm ./cmd/atc/internal/testing/apis/backend/v2/dev && \
  GOTOOLCHAIN=auto GOOS=wasip1 GOARCH=wasm go build -o ./cmd/atc/internal/testing/wasmcache/wasm/converter.wasm ./cmd/atc/internal/testing/apis/backend/converter && \
  GOTOOLCHAIN=auto go build -o ./bin/server ./cmd/atc/internal/testing/wasmcache

FROM alpine

COPY --from=builder /app/bin/server ./server

ENTRYPOINT ["./server"]

