FROM --platform=$BUILDPLATFORM golang:1.26-alpine AS builder

ARG TARGETOS
ARG TARGETARCH

WORKDIR /cmp

COPY go.mod go.sum ./

RUN go mod download

COPY ./cmd/yokecd ./cmd/yokecd
COPY ./internal ./internal
COPY ./pkg ./pkg

RUN GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -o /bin/yokecd ./cmd/yokecd

FROM golang:1.26-alpine

COPY --from=builder /bin/yokecd /bin/yokecd
COPY ./cmd/yokecd/plugin.yaml /home/argocd/cmp-server/config/plugin.yaml

RUN chmod -R 777 /go
