FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY ./cmd/atc ./cmd/atc
COPY ./internal ./internal
COPY ./pkg ./pkg

RUN go build -o /bin/atc ./cmd/atc 

FROM alpine

COPY --from=builder /bin/atc ./atc

ENTRYPOINT ["./atc"]

