FROM golang:1.24-alpine AS builder

WORKDIR /cmp

COPY go.mod go.sum ./

RUN go mod download

COPY ./cmd/yokecd ./cmd/yokecd
COPY ./internal ./internal
COPY ./pkg ./pkg

RUN go build -o /bin/yokecd ./cmd/yokecd

FROM golang:1.24-alpine

COPY --from=builder /bin/yokecd /bin/yokecd
COPY ./cmd/yokecd/plugin.yaml /home/argocd/cmp-server/config/plugin.yaml

RUN \
  chmod -R 777 /go && \
  mkdir -p /.cache/wasm && \
  mkdir -p /.cache/compiled && \
  chmod -R 777 /.cache

