FROM --platform=$BUILDPLATFORM golang:1.26-alpine AS builder

ARG TARGETOS
ARG TARGETARCH

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY ./cmd/atc ./cmd/atc
COPY ./internal ./internal
COPY ./pkg ./pkg

RUN GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -o /bin/atc ./cmd/atc 

FROM alpine

COPY --from=builder /bin/atc ./atc

ENTRYPOINT ["./atc"]

