FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN GOTOOLCHAIN=auto go mod download

COPY ./cmd/atc ./cmd/atc
COPY ./internal ./internal
COPY ./pkg ./pkg

RUN GOTOOLCHAIN=auto go build -o /bin/atc ./cmd/atc 

FROM alpine

COPY --from=builder /bin/atc ./atc

ENTRYPOINT ["./atc"]

