# Ironically the task runner is itself a dev dependency of the project.
# To install it run the following command:
#
# go install github.com/go-task/task/v3/cmd/task@latest

version: "3"

tasks:
  fmt:
    cmds:
      - goimports -local github.com/yokecd/yoke -w .
      - goimports -local k8s.io -w .
      - goimports -local github.com/davidmdm -w .
      - gofumpt -w .

  test:
    cmds:
      - go test -timeout 20m -p 1 -count 1 -v ./...

  update-tools:
    cmds:
      - go install sigs.k8s.io/kind@latest

  update-deps:
    cmds:
      - go get -u ./...
      - go get github.com/tetratelabs/wazero@v1.6.0
      - go mod tidy

  update-yokecd-argo:
    cmds:
      - go install ./cmd/helm2go
      - rm -rf ./cmd/yokecd-installer/argocd
      - helm2go -repo https://argoproj.github.io/argo-helm/argo-cd -outdir ./cmd/yokecd-installer/argocd
      - task fmt

  wasm:
    cmds:
      - task: kube
      - task: pg
      - task: redis

  yokecd-installer:
    cmds:
      - GOOS=wasip1 GOARCH=wasm go build -o yokecd-installer.wasm ./cmd/yokecd-installer

  kube:
    cmds:
      - GOOS=wasip1 GOARCH=wasm go build -o basic.wasm ./examples/basic

  pg:
    cmds:
      - GOOS=wasip1 GOARCH=wasm go build -o pg.wasm ./examples/embeddedfs

  redis:
    cmds:
      - GOOS=wasip1 GOARCH=wasm go build -o redis.wasm ./examples/redis

  build-cli: # Handy for contributers
    cmds:
      - go build ./cmd/yoke
