name: test -> build -> release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-release:
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Setup Go environment
        uses: actions/setup-go@v3.3.1
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
          cache: true

      - name: Run tests
        shell: bash
        run: |
          go install github.com/go-task/task/v3/cmd/task@latest
          go install sigs.k8s.io/kind@latest

          task test

      - name: Build and Release Flights
        if: github.ref == 'refs/heads/main'
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
          GITHUB_ACTOR: davidmdm
        run: |
          go run ./cmd/internal/releaser \
            -latest \
            -cli \
            -wasm yokecd-installer \
            -wasm atc-installer \
            -docker atc \
            -docker yokecd
